In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1.shape

(10,)

In [4]:
a2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
a2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
a2.shape

(10, 1)

In [6]:
a3=np.array([[0,1,2,3,4],
             [1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])
a3.shape

(4, 5)

In [7]:
a4=a3.reshape(2,2,5)
a4

array([[[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [8]:
a1.ndim

1

In [9]:
a3.size

20

In [10]:
import pandas as pd
df=pd.DataFrame(a3)
df

0  1  2  3  4
0  0  1  2  3  4
1  1  2  3  4  5
2  2  3  4  5  6
3  3  4  5  6  7

In [11]:
a4=np.ones((2,4))
a4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
a4.dtype

dtype('float64')

In [13]:
a4.astype('int64')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [14]:
a5=np.zeros((2,4),dtype='int64')
a5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [15]:
a6=np.arange(0,10,2,dtype='int64')
a6

array([0, 2, 4, 6, 8], dtype=int64)

In [16]:
a_rand=np.random.randint(0,10,5)
a_rand

array([0, 7, 6, 7, 5])

In [17]:
a2_rand=np.random.randint(0,10,size=(2,5))
a2_rand

array([[7, 7, 3, 7, 1],
       [6, 1, 4, 6, 7]])

In [18]:
a3_rand=np.random.random((2,4))

In [19]:
a3_rand

array([[0.27487667, 0.58990275, 0.18296922, 0.90396338],
       [0.5759146 , 0.94444716, 0.71265269, 0.40874303]])

In [20]:
a3_rand.shape

(2, 4)

In [21]:
a3_rand.size

8

In [22]:
a4_rand=np.random.rand(4,5)

In [23]:
a4_rand

array([[0.3639341 , 0.21765753, 0.83943632, 0.23679163, 0.96040231],
       [0.67882489, 0.13316636, 0.83865615, 0.62965174, 0.92902456],
       [0.12933845, 0.16419286, 0.5661388 , 0.57003531, 0.41910836],
       [0.77537063, 0.29850771, 0.5470239 , 0.65703173, 0.94776353]])

In [24]:
a5=np.unique(np.random.randint(0,100,size=(2,4)))
a5

array([ 2, 47, 54, 55, 72, 79, 82, 95])

In [25]:
a5=np.random.randint(2,5)
a5

3

In [26]:
a6=np.array([1,2,3,4,5,6])
a7=np.array([[1,2,3],
             [9,8,7]])

In [27]:
a6=a6.reshape(np.shape(a7))
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.random.seed(123)
sale=np.random.randint(0,100,size=(5,3))
sale

array([[66, 92, 98],
       [17, 83, 57],
       [86, 97, 96],
       [47, 73, 32],
       [46, 96, 25]])

In [34]:
np.random.seed(123)
price=np.random.randint(0,100,size=(1,3))
price

array([[66, 92, 98]])

In [35]:
sale=pd.DataFrame(sale,
                  index=["mon","tue","wed","thu","fri"],
                  columns=["item1","item2","item3"])
sale

item1  item2  item3
mon     66     92     98
tue     17     83     57
wed     86     97     96
thu     47     73     32
fri     46     96     25

In [37]:
rate=pd.DataFrame(price,columns=["item1","item2","item3"])
rate

item1  item2  item3
0     66     92     98

In [38]:
 profit=pd.DataFrame()

In [41]:
profit=np.sum(np.multiply(sale,rate),axis=1)
profit

C:\Users\hp\AppData\Local\Temp\ipykernel_78608\3223493182.py:1: FutureWarning: Calling a ufunc on non-aligned DataFrames (or DataFrame/Series combination). Currently, the indices are ignored and the result takes the index/columns of the first DataFrame. In the future , the DataFrames/Series will be aligned before applying the ufunc.
Convert one of the arguments to a NumPy array (eg 'ufunc(df1, np.asarray(df2)') to keep the current behaviour, or align manually (eg 'df1, df2 = df1.align(df2)') before passing to the ufunc to obtain the future behaviour and silence this warning.
  profit=np.sum(np.multiply(sale,rate),axis=1)


mon    22424
tue    14344
wed    24008
thu    12954
fri    14318
dtype: int64

In [43]:
profit1=np.dot(rate,sale.T)
profit1

array([[22424, 14344, 24008, 12954, 14318]])