In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1.shape

(10,)

In [4]:
a2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
a2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [5]:
a2.shape

(10, 1)

In [6]:
a3=np.array([[0,1,2,3,4],
             [1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])
a3.shape

(4, 5)

In [7]:
a4=a3.reshape(2,2,5)
a4

array([[[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [8]:
a1.ndim

1

In [9]:
a3.size

20

In [10]:
import pandas as pd
df=pd.DataFrame(a3)
df

0  1  2  3  4
0  0  1  2  3  4
1  1  2  3  4  5
2  2  3  4  5  6
3  3  4  5  6  7

In [11]:
a4=np.ones((2,4))
a4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
a4.dtype

dtype('float64')

In [13]:
a4.astype('int64')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [14]:
a5=np.zeros((2,4),dtype='int64')
a5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [16]:
a6=np.arange(0,10,2,dtype='int64')
a6

array([0, 2, 4, 6, 8], dtype=int64)

In [19]:
a_rand=np.random.randint(0,10,5)
a_rand

array([2, 7, 7, 3, 5])

In [25]:
a2_rand=np.random.randint(0,10,size=(2,5))
a2_rand

array([[5, 6, 1, 9, 8],
       [8, 7, 3, 8, 1]])

In [26]:
a3_rand=np.random.random((2,4))

In [27]:
a3_rand

array([[0.90728448, 0.09627166, 0.36244114, 0.45978417],
       [0.51664508, 0.07899285, 0.13202829, 0.54911637]])

In [28]:
a3_rand.shape

(2, 4)

In [29]:
a3_rand.size

8

In [30]:
a4_rand=np.random.rand(4,5)

In [31]:
a4_rand

array([[0.56308035, 0.60352611, 0.7540481 , 0.14600099, 0.23455343],
       [0.59188275, 0.8276531 , 0.88442015, 0.53550395, 0.43170382],
       [0.4116553 , 0.7217411 , 0.78061163, 0.22355255, 0.25673331],
       [0.00234864, 0.3731175 , 0.9108793 , 0.04013209, 0.14450384]])