In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a1.shape

(10,)

In [5]:
a2=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
a2

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [6]:
a2.shape

(10, 1)

In [7]:
a3=np.array([[0,1,2,3,4],
             [1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])
a3.shape

(4, 5)

In [12]:
a3.reshape(2,2,5)

array([[[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])